/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Lemmatron;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LemmatronApi
 */
public class LemmatronApiTest {

    private final LemmatronApi api = new LemmatronApi();

    
    /**
     * Apply optional filters to Lemmatron response
     *
     *  Retrieve available [lemmas](documentation/glossary?term&#x3D;lemma) for a given [inflected](documentation/glossary?term&#x3D;inflection) wordform. Filter results by categories.      &lt;div id&#x3D;\&quot;lemmatron_filters\&quot;&gt;&lt;/div&gt; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void inflectionsSourceLangWordIdFiltersGetTest() throws ApiException {
        String sourceLang = null;
        String wordId = null;
        List<String> filters = null;
        String appId = null;
        String appKey = null;
        // Lemmatron response = api.inflectionsSourceLangWordIdFiltersGet(sourceLang, wordId, filters, appId, appKey);

        // TODO: test validations
    }
    
    /**
     * Check a word exists in the dictionary and retrieve its root form
     *
     *  Use this to check if a word exists in the dictionary, or what &#39;root&#39; form it links to (e.g., swimming &gt; swim). The response tells you the possible [lemmas](documentation/glossary?term&#x3D;lemma) for a given [inflected](documentation/glossary?term&#x3D;inflection) word. This can then be combined with other endpoints to retrieve more information.    &lt;div id&#x3D;\&quot;lemmatron\&quot;&gt;&lt;/div&gt; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void inflectionsSourceLangWordIdGetTest() throws ApiException {
        String sourceLang = null;
        String wordId = null;
        String appId = null;
        String appKey = null;
        // Lemmatron response = api.inflectionsSourceLangWordIdGet(sourceLang, wordId, appId, appKey);

        // TODO: test validations
    }
    
}
