/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Arrayofstrings;


/**
 * A mapping of filters available per endpoints.
 */
@ApiModel(description = "A mapping of filters available per endpoints.")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-05T18:00:32.106-05:00")
public class FiltersResults   {
  @SerializedName("entries")
  private Arrayofstrings entries = null;

  @SerializedName("inflections")
  private Arrayofstrings inflections = null;

  @SerializedName("translations")
  private Arrayofstrings translations = null;

  @SerializedName("wordlist")
  private Arrayofstrings wordlist = null;

  public FiltersResults entries(Arrayofstrings entries) {
    this.entries = entries;
    return this;
  }

   /**
   * A list of filters available for Retrieve Entry endpoint
   * @return entries
  **/
  @ApiModelProperty(example = "null", value = "A list of filters available for Retrieve Entry endpoint")
  public Arrayofstrings getEntries() {
    return entries;
  }

  public void setEntries(Arrayofstrings entries) {
    this.entries = entries;
  }

  public FiltersResults inflections(Arrayofstrings inflections) {
    this.inflections = inflections;
    return this;
  }

   /**
   * A list of filters available for LEMMATRON endpoint
   * @return inflections
  **/
  @ApiModelProperty(example = "null", value = "A list of filters available for LEMMATRON endpoint")
  public Arrayofstrings getInflections() {
    return inflections;
  }

  public void setInflections(Arrayofstrings inflections) {
    this.inflections = inflections;
  }

  public FiltersResults translations(Arrayofstrings translations) {
    this.translations = translations;
    return this;
  }

   /**
   * A list of filters available for Translations endpoint
   * @return translations
  **/
  @ApiModelProperty(example = "null", value = "A list of filters available for Translations endpoint")
  public Arrayofstrings getTranslations() {
    return translations;
  }

  public void setTranslations(Arrayofstrings translations) {
    this.translations = translations;
  }

  public FiltersResults wordlist(Arrayofstrings wordlist) {
    this.wordlist = wordlist;
    return this;
  }

   /**
   * A list of filters available for Translations endpoint
   * @return wordlist
  **/
  @ApiModelProperty(example = "null", value = "A list of filters available for Translations endpoint")
  public Arrayofstrings getWordlist() {
    return wordlist;
  }

  public void setWordlist(Arrayofstrings wordlist) {
    this.wordlist = wordlist;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FiltersResults filtersResults = (FiltersResults) o;
    return Objects.equals(this.entries, filtersResults.entries) &&
        Objects.equals(this.inflections, filtersResults.inflections) &&
        Objects.equals(this.translations, filtersResults.translations) &&
        Objects.equals(this.wordlist, filtersResults.wordlist);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entries, inflections, translations, wordlist);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FiltersResults {\n");
    
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    inflections: ").append(toIndentedString(inflections)).append("\n");
    sb.append("    translations: ").append(toIndentedString(translations)).append("\n");
    sb.append("    wordlist: ").append(toIndentedString(wordlist)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

