/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * Ngrams matching the given options
 */
@ApiModel(description = "Ngrams matching the given options")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-05T18:00:32.106-05:00")
public class NgramsResultResults   {
  @SerializedName("frequency")
  private Integer frequency = null;

  @SerializedName("tokens")
  private List<String> tokens = new ArrayList<String>();

  public NgramsResultResults frequency(Integer frequency) {
    this.frequency = frequency;
    return this;
  }

   /**
   * The number of times the ngram (a sequence of n words) appears in the corpus
   * @return frequency
  **/
  @ApiModelProperty(example = "null", required = true, value = "The number of times the ngram (a sequence of n words) appears in the corpus")
  public Integer getFrequency() {
    return frequency;
  }

  public void setFrequency(Integer frequency) {
    this.frequency = frequency;
  }

  public NgramsResultResults tokens(List<String> tokens) {
    this.tokens = tokens;
    return this;
  }

  public NgramsResultResults addTokensItem(String tokensItem) {
    this.tokens.add(tokensItem);
    return this;
  }

   /**
   * A list of tokens
   * @return tokens
  **/
  @ApiModelProperty(example = "null", required = true, value = "A list of tokens")
  public List<String> getTokens() {
    return tokens;
  }

  public void setTokens(List<String> tokens) {
    this.tokens = tokens;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NgramsResultResults ngramsResultResults = (NgramsResultResults) o;
    return Objects.equals(this.frequency, ngramsResultResults.frequency) &&
        Objects.equals(this.tokens, ngramsResultResults.tokens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(frequency, tokens);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NgramsResultResults {\n");
    
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

