/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SentencesLexicalEntry;
import java.util.ArrayList;
import java.util.List;


/**
 * Description of a word
 */
@ApiModel(description = "Description of a word")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-05T18:00:32.106-05:00")
public class SentencesEntry   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("lexicalEntries")
  private List<SentencesLexicalEntry> lexicalEntries = new ArrayList<SentencesLexicalEntry>();

  @SerializedName("type")
  private String type = null;

  @SerializedName("word")
  private String word = null;

  public SentencesEntry id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The identifier of a word
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "The identifier of a word")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SentencesEntry language(String language) {
    this.language = language;
    return this;
  }

   /**
   * IANA language code
   * @return language
  **/
  @ApiModelProperty(example = "null", required = true, value = "IANA language code")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public SentencesEntry lexicalEntries(List<SentencesLexicalEntry> lexicalEntries) {
    this.lexicalEntries = lexicalEntries;
    return this;
  }

  public SentencesEntry addLexicalEntriesItem(SentencesLexicalEntry lexicalEntriesItem) {
    this.lexicalEntries.add(lexicalEntriesItem);
    return this;
  }

   /**
   * A grouping of various senses in a specific language, and a lexical category that relates to a word
   * @return lexicalEntries
  **/
  @ApiModelProperty(example = "null", required = true, value = "A grouping of various senses in a specific language, and a lexical category that relates to a word")
  public List<SentencesLexicalEntry> getLexicalEntries() {
    return lexicalEntries;
  }

  public void setLexicalEntries(List<SentencesLexicalEntry> lexicalEntries) {
    this.lexicalEntries = lexicalEntries;
  }

  public SentencesEntry type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The json object type. Could be 'headword', 'inflection' or 'phrase'
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "The json object type. Could be 'headword', 'inflection' or 'phrase'")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public SentencesEntry word(String word) {
    this.word = word;
    return this;
  }

   /**
   * A given written or spoken realisation of a an entry, lowercased.
   * @return word
  **/
  @ApiModelProperty(example = "null", required = true, value = "A given written or spoken realisation of a an entry, lowercased.")
  public String getWord() {
    return word;
  }

  public void setWord(String word) {
    this.word = word;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SentencesEntry sentencesEntry = (SentencesEntry) o;
    return Objects.equals(this.id, sentencesEntry.id) &&
        Objects.equals(this.language, sentencesEntry.language) &&
        Objects.equals(this.lexicalEntries, sentencesEntry.lexicalEntries) &&
        Objects.equals(this.type, sentencesEntry.type) &&
        Objects.equals(this.word, sentencesEntry.word);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, language, lexicalEntries, type, word);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SentencesEntry {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    lexicalEntries: ").append(toIndentedString(lexicalEntries)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    word: ").append(toIndentedString(word)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

