/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Link to a sense of a specific entry in the thesaurus Dictionary
 */
@ApiModel(description = "Link to a sense of a specific entry in the thesaurus Dictionary")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-05T18:00:32.106-05:00")
public class ThesaurusLink   {
  @SerializedName("entry_id")
  private String entryId = null;

  @SerializedName("sense_id")
  private String senseId = null;

  public ThesaurusLink entryId(String entryId) {
    this.entryId = entryId;
    return this;
  }

   /**
   * identifier of a word
   * @return entryId
  **/
  @ApiModelProperty(example = "null", required = true, value = "identifier of a word")
  public String getEntryId() {
    return entryId;
  }

  public void setEntryId(String entryId) {
    this.entryId = entryId;
  }

  public ThesaurusLink senseId(String senseId) {
    this.senseId = senseId;
    return this;
  }

   /**
   * identifier of a sense
   * @return senseId
  **/
  @ApiModelProperty(example = "null", required = true, value = "identifier of a sense")
  public String getSenseId() {
    return senseId;
  }

  public void setSenseId(String senseId) {
    this.senseId = senseId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThesaurusLink thesaurusLink = (ThesaurusLink) o;
    return Objects.equals(this.entryId, thesaurusLink.entryId) &&
        Objects.equals(this.senseId, thesaurusLink.senseId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entryId, senseId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThesaurusLink {\n");
    
    sb.append("    entryId: ").append(toIndentedString(entryId)).append("\n");
    sb.append("    senseId: ").append(toIndentedString(senseId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

